FROM python AS arah-env-build

WORKDIR /app

RUN apt-get update
RUN apt-get install -y curl git python3-pip python3-dev python-is-python3
RUN rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/sheetalkamthe55/arah.git
RUN curl -s https://raw.githubusercontent.com/sheetalkamthe55/arah/main/requirements.txt | xargs pip install
