services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - 27017:27017
  streamlit:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongo-express
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 'all'
    working_dir: /app/ARHChat
    ports:
      - 8503:8503
    # volumes:
    #   - <local metadata directory>:/app/ARHChat/metadata
    #   - <local secret.toml file path>:/app/ARHChat/.streamlit/secrets.toml
    command: ["streamlit", "run", "app.py", "--server.port=8503", "--server.address=0.0.0.0"]