services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - 27017:27017
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data
  llama_cpp_server:
    image: llama-cpp-docker
    environment:
      - GGML_CUDA_NO_PINNED=1
      - LLAMA_CTX_SIZE=2048
      - LLAMA_MODEL=/models/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf
      - LLAMA_N_GPU_LAYERS=99
    volumes:
      - ./models:/models
    ports:
      - target: 8009
        published: 8009
        mode: host
  streamlit:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - qdrant
      - llama_cpp_server
    working_dir: /app/ARHChat
    ports:
      - 8503:8503
    volumes:
      - ~/Project/ARHChat/metadata:/app/ARHChat/metadata
      - ~/Project/ARHChat/.streamlit/secrets.toml:/app/ARHChat/.streamlit/secrets.toml
    command: ["streamlit", "run", "app.py", "--server.port=8503", "--server.address=0.0.0.0"]
  