FROM python

RUN apt-get update
RUN apt-get install -y curl git python3-pip python3-dev python-is-python3
RUN rm -rf /var/lib/apt/lists/*

RUN pip3 install llama_cpp_python[server]==0.2.76

RUN apt-get update && apt-get install -y musl