FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

RUN apt-get update
RUN apt-get install -y curl git python3-pip python3-dev python-is-python3
RUN rm -rf /var/lib/apt/lists/*

ENV CUDA_DOCKER_ARCH=all
ENV LLAMA_CUBLAS=1

ENV CMAKE_ARGS="-DLLAMA_CUBLAS=ON"
RUN pip3 install llama_cpp_python[server]==0.2.76
