services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - 27017:27017
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data
  llama_cpp_server:
    build: 
      dockerfile: Dockerfile-cpu
    command: python3 -m llama_cpp.server --model /models/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf --port 8009 --host 0.0.0.0 --n_ctx 8000 --chat_format chatml
    ports:
      - target: 8009
        published: 8009
        mode: host
    volumes:
      - ./models:/models
  arahui:
    build:
      dockerfile: Dockerfile-arah
      no_cache: true
    depends_on:
      - mongo
      - qdrant
      - llama_cpp_server
    working_dir: /app/arah/api/ui
    ports:
      - 8503:8503
    volumes:
      - /Users/sheetalkamthe/Documents/Thesis/Project/arah/api/ui/metadata:/app/arah/api/ui/metadata
      - /Users/sheetalkamthe/Documents/Thesis/Project/arah/api/ui/.streamlit/secrets.toml:/app/arah/api/ui/.streamlit/secrets.toml
    command: ["streamlit", "run", "app.py", "--server.port=8503", "--server.address=0.0.0.0"]
  arahapi:
      build:
        dockerfile: Dockerfile-arah
        no_cache: true
      depends_on:
        - mongo
        - qdrant
        - llama_cpp_server
      working_dir: /app/arah/api
      ports:
        - 8505:8505
      volumes:
        - /Users/sheetalkamthe/Documents/Thesis/Project/arah/settings.yaml:/app/arah/settings.yaml
      command: ["uvicorn", "main:app", "--port 8505"]
  
#  uvicorn main:app --port 8505