services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - 27017:27017
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data
  llama_cpp_server:
    build: 
      dockerfile: Dockerfile-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 'all'
    command: python3 -m llama_cpp.server --model /models/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf --port 8009 --host 0.0.0.0 --n_ctx 8009 --chat_format chatml
    ports:
      - target: 8009
        published: 8009
        mode: host
    volumes:
      - ./models:/models
  streamlit:
    build:
      dockerfile: Dockerfile-streamlit
    depends_on:
      - mongo
      - qdrant
      - llama_cpp_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 'all'
    working_dir: /app/arah
    ports:
      - 8503:8503
    volumes:
      - ~/Project/ARHChat/arah/metadata:/app/arah/metadata
      - ~/Project/ARHChat/arah/.streamlit/secrets.toml:/app/arah/.streamlit/secrets.toml
    command: ["streamlit", "run", "app.py", "--server.port=8503", "--server.address=0.0.0.0"]