FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

WORKDIR /app

# install python
RUN apt-get update
RUN apt-get install -y curl git python3-pip python3-dev python-is-python3
RUN rm -rf /var/lib/apt/lists/*

# clone streamlit app
RUN git clone https://github.com/abc.git
RUN pip install gnews
# exclude gnews because of requests dependency
RUN curl -s https://raw.githubusercontent.com/abc/main/requirements.txt | grep -v gnews | xargs pip install